/* ***********META CHARACTERS****************
* [abc] A single character of a...
* [^abc] A character except a..
* [a-z] Matches any characters between a and z, including a and z.
*/
// [abc]: A single character of a...
